### ISSUE TITLE
Useless left text entry field

### ISSUE THREAD

**Issue by dikonov** [cboxdoerfer/ddb_quick_search#2]
This plugin has two text entry fields. One is the main search quiery (right) entry and works well. The other (left) has no obvious function and cannot be hidden. 

Can the useless left field be removed?

**Comment by harpalus-honestus** [comment]
I would also like to see the left entry field removed. I guess the relevant code is somewhere [here](https://github.com/cboxdoerfer/ddb_quick_search/blob/master/main.c#L885) (and following lines), but I fail to understand what to change exactly (after having looked up the used objects etc. [here](https://developer.gnome.org/gtk3/stable/)). If the author could give us a hint, I'll gladly make the change myself.

**Comment by cboxdoerfer** [comment]
Thx for reporting. Should be fixed now.

**Comment by harpalus-honestus** [comment]
That was quick! Thanks!
